### ISSUE TITLE
tauri + leptos + wasm renderer. Error:

### ISSUE THREAD

**Issue by Groni3000** [yuankunzhang/charming#74]
Cargo.toml
```toml
[dependencies]
leptos = { version = "0.6", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1.7"
leptos-chartistry = "0.1.7"
charming = { version = "0.3.1", features = ["wasm"] }

[workspace]
members = ["src-tauri"]
```

src/main.rs
```rust
pub mod components;

use components::chart::ChartExample;
use leptos::*;

fn main() {
    console_error_panic_hook::set_once();
    mount_to_body(move || {
        view! {
            <main class="container">
                <ChartExample/>
            </main>
        }
    })
}
```

src/components/chart.rs
```rust
use charming::{
    component::{Axis, Title},
    datatype::DataPointItem,
    df,
    element::{AxisType, ItemStyle},
    series::Bar,
    Chart, WasmRenderer,
};
use leptos::logging;
use leptos::*;

pub fn chart() -> Chart {
    Chart::new()
        .title(Title::new().text("Chart example"))
        .x_axis(
            Axis::new()
                .type_(AxisType::Category)
                .data(vec!["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]),
        )
        .y_axis(Axis::new().type_(AxisType::Value))
        .series(Bar::new().data(df![
            120,
            DataPointItem::new(200).item_style(ItemStyle::new().color("#a90000")),
            150,
            80,
            70,
            110,
            130,
        ]))
}

#[component]
pub fn ChartExample() -> impl IntoView {
    let action = create_action(|_input: &()| async {
        let chart = chart();
        WasmRenderer::new(600, 400).render("chart", &chart).unwrap();
    });
    // action.dispatch(());

    view! {
        <div>
        <button on:click=move |_| {
                logging::log!("Hello, world!");
                action.dispatch(());
            }>"Show chart"</button>
            <div id="chart"></div>
        </div>
    }
}
```

After clicking button I get:
![image](https://github.com/user-attachments/assets/5571b031-b0e5-435e-ba79-6ebfbe7e8f9e)

I tried `npm install echarts`. Closed and opened VSCode again, but it didn't help.
